name: Ejecutar test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend Tests
        run: |
          pip install -r requirements.txt
          pytest test/backend/unit/
